#!/bin/zsh
# Assemble one Ripes source file from tables.s and solver.s.
#   build_asm.sh CUBE [EXPECT] [RENDER]
#     CUBE    14-digit state, e.g. 21345671111111
#     EXPECT  expected number of moves, checked inside the program (-1 = skip)
#     RENDER  1 for the LED Matrix build (GUI only), 0 for the CLI build
# Writes build/solver-CUBE[-render].s (or $OUT if set) and prints its path.
set -eu
cd ${0:A:h}
cube=$1 expect=${2:--1} render=${3:-0}
mkdir -p build
out=build/solver-$cube.s
[[ $render == 1 ]] && out=build/solver-$cube-render.s
out=${OUT:-$out}
# Ripes has no .if: drop the lines between the RENDER markers unless RENDER=1.
keep='{ print }'
[[ $render == 1 ]] || keep='/^# >>> RENDER/ { skip = 1 } !skip { print } /^# <<< RENDER/ { skip = 0 }'
{
    echo "# Generated by build_asm.sh from tables.s and solver.s (RENDER=$render). Do not edit."
    cat tables.s
    sed -e "s/@CUBE@/$cube/" -e "s/@EXPECT@/$expect/" solver.s | awk "$keep"
} > $out
echo $out
