/* Read-only tables generated by tools/gen_tables.c. */
#ifndef TABLES_H
#define TABLES_H
#include <stdint.h>

enum { NPERM = 5040, NORI = 729, NPAIR = 42 };

extern const uint16_t perm_q[3 * NPERM]; /* perm rank after a quarter turn */
extern const uint16_t ori_q[3 * NORI];   /* orientation rank after a quarter turn */
extern const uint8_t pair_q[3 * NPAIR];  /* rank of the positions of cubies 3, 6 */
extern const uint8_t hperm[NPERM];       /* distance, permutation abstraction */
extern const uint8_t pdb[NPAIR * 1024];  /* distance, (pair, orientation); index pair << 10 | o */
#endif
