/* Generate the read-only tables for the RV32I solver and check them.
 *
 * Writes ../rv32/tables.c (C arrays) and ../rv32/tables.s (assembler data),
 * and checks on the host:
 *   H1  max(pdb, hperm) <= exact distance for all 3,674,160 states
 *   H2  every table is fully populated, with its maximum and solved entry
 *       verified; every transition row is a permutation whose fourth power
 *       is the identity
 * Tables:
 *   perm_q[3][5040]  uint16  permutation rank after a quarter turn of face f
 *   ori_q[3][729]    uint16  orientation rank after a quarter turn
 *   pair_q[3][42]    uint8   rank of the positions of cubies 3 and 6
 *   hperm[5040]      uint8   exact distance in the permutation abstraction
 *   pdb[42][1024]    uint8   exact distance in the (pair, orientation)
 *                            abstraction; columns 729..1023 are padding (0xFF)
 *                            so that the index is pair << 10 | orientation
 */
#include "model.h"

static uint8_t hperm[NPERM], pdb[NPAIR][PDB_STRIDE];

static int fail(const char *what)
{
    printf("FAIL: %s\n", what);
    exit(1);
}

static void build_hperm(void)
{
    static uint16_t q[NPERM];
    int head = 0, tail = 0;
    memset(hperm, 0xFF, sizeof hperm);
    hperm[0] = 0;
    q[tail++] = 0;
    while (head < tail) {
        int u = q[head++];
        for (int f = 0; f < 3; f++)
            for (int t = 0, v = u; t < 3; t++) {
                v = perm_q[f][v];
                if (hperm[v] == 0xFF) { hperm[v] = (uint8_t) (hperm[u] + 1); q[tail++] = (uint16_t) v; }
            }
    }
}

static void build_pdb(int solved_pair)
{
    static uint32_t q[NPAIR * NORI];
    int head = 0, tail = 0;
    memset(pdb, 0xFF, sizeof pdb);
    pdb[solved_pair][0] = 0;
    q[tail++] = (uint32_t) solved_pair << 10;
    while (head < tail) {
        uint32_t u = q[head++], r = u >> 10, o = u & 1023;
        for (int f = 0; f < 3; f++) {
            uint32_t nr = r, no = o;
            for (int t = 0; t < 3; t++) {
                nr = pair_q[f][nr];
                no = ori_q[f][no];
                if (pdb[nr][no] == 0xFF) { pdb[nr][no] = (uint8_t) (pdb[r][o] + 1); q[tail++] = nr << 10 | no; }
            }
        }
    }
}

/* H2 for a transition table of n entries per face. */
static void check_transition(const char *name, int n, int (*at)(int, int))
{
    for (int f = 0; f < 3; f++) {
        char *seen = calloc((size_t) n, 1);
        for (int i = 0; i < n; i++) {
            int v = at(f, i);
            if (v < 0 || v >= n || seen[v]++) fail(name);
            int w = i;
            for (int t = 0; t < 4; t++) w = at(f, w);
            if (w != i) fail(name);
        }
        free(seen);
    }
    printf("H2 %-7s: 3 faces x %d entries, each a permutation, fourth power is identity\n", name, n);
}
static int at_perm(int f, int i) { return perm_q[f][i]; }
static int at_ori(int f, int i) { return ori_q[f][i]; }
static int at_pair(int f, int i) { return pair_q[f][i]; }

static void emit(int solved_pair)
{
    FILE *c = fopen("../rv32/tables.c", "w"), *s = fopen("../rv32/tables.s", "w");
    if (!c || !s) fail("cannot write ../rv32/tables.{c,s}");
    fprintf(c, "/* Generated by tools/gen_tables.c. Do not edit. */\n#include \"tables.h\"\n\n");
    fprintf(s, "# Generated by tools/gen_tables.c. Do not edit.\n    .data\n");
    fprintf(s, "    .equ SOLVED_PAIR, %d\n", solved_pair);
#define ARRAY(cname, ctype, sdir, count, expr)                                  \
    do {                                                                       \
        fprintf(c, "const %s %s[%d] = {", ctype, cname, count);               \
        fprintf(s, "%s:", cname);                                              \
        for (int i = 0; i < (count); i++) {                                    \
            if (i % 16 == 0) { fprintf(c, "\n   "); fprintf(s, "\n    %s ", sdir); } \
            else fprintf(s, ",");                                              \
            fprintf(c, " %d,", (int) (expr));                                  \
            fprintf(s, "%d", (int) (expr));                                    \
        }                                                                      \
        fprintf(c, "\n};\n");                                                  \
        fprintf(s, "\n");                                                      \
    } while (0)
    /* halfword tables first so that they stay 2-byte aligned */
    ARRAY("perm_q", "uint16_t", ".half", 3 * NPERM, perm_q[i / NPERM][i % NPERM]);
    ARRAY("ori_q", "uint16_t", ".half", 3 * NORI, ori_q[i / NORI][i % NORI]);
    ARRAY("pair_q", "uint8_t", ".byte", 3 * NPAIR, pair_q[i / NPAIR][i % NPAIR]);
    ARRAY("hperm", "uint8_t", ".byte", NPERM, hperm[i]);
    ARRAY("pdb", "uint8_t", ".byte", NPAIR * PDB_STRIDE, pdb[i >> 10][i & 1023]);
    fclose(c);
    fclose(s);
    printf("tables: perm_q %d B, ori_q %d B, pair_q %d B, hperm %d B, pdb %d B, total %d B\n",
           3 * NPERM * 2, 3 * NORI * 2, 3 * NPAIR, NPERM, NPAIR * PDB_STRIDE,
           3 * NPERM * 2 + 3 * NORI * 2 + 3 * NPAIR + NPERM + NPAIR * PDB_STRIDE);
}

int main(void)
{
    uint8_t solved[CUBIES] = {0, 1, 2, 3, 4, 5, 6};
    int solved_pair = pair_rank(solved), diameter, maxh = 0;

    build_transitions();
    check_transition("perm_q", NPERM, at_perm);
    check_transition("ori_q", NORI, at_ori);
    check_transition("pair_q", NPAIR, at_pair);

    build_hperm();
    for (int i = 0; i < NPERM; i++) {
        if (hperm[i] == 0xFF) fail("hperm not fully populated");
        if (hperm[i] > maxh) maxh = hperm[i];
    }
    if (hperm[0] != 0) fail("hperm solved entry");
    printf("H2 hperm  : %d entries populated, solved entry 0, max %d\n", NPERM, maxh);

    build_pdb(solved_pair);
    maxh = 0;
    for (int r = 0; r < NPAIR; r++)
        for (int o = 0; o < PDB_STRIDE; o++) {
            if (o < NORI && pdb[r][o] == 0xFF) fail("pdb not fully populated");
            if (o >= NORI && pdb[r][o] != 0xFF) fail("pdb padding written");
            if (o < NORI && pdb[r][o] > maxh) maxh = pdb[r][o];
        }
    if (pdb[solved_pair][0] != 0) fail("pdb solved entry");
    printf("H2 pdb    : %d x %d entries populated, solved entry [%d][0] = 0, max %d, padding 0xFF\n",
           NPAIR, NORI, solved_pair, maxh);

    uint8_t *dist = exact_distances(&diameter);
    uint64_t sum = 0, tight = 0;
    state_t st;
    for (uint32_t s = 0; s < NSTATE; s++) {
        unrank_state(s, &st);
        int a = pdb[pair_rank(st.p)][s % NORI], b = hperm[s / NORI], h = a > b ? a : b;
        if (h > dist[s]) fail("H1: heuristic exceeds exact distance");
        if ((h == 0) != (s == 0)) fail("H1: h is 0 exactly at the solved state");
        sum += h;
        tight += h == dist[s];
    }
    printf("H1 h <= d : all %d states (diameter %d); mean h %.3f, h == d for %llu states\n",
           NSTATE, diameter, (double) sum / NSTATE, (unsigned long long) tight);
    emit(solved_pair);
    return 0;
}
